import React from 'react';
import Head from "next/head";
import Link from "next/link";

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title className='font-mono'>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="py-10 mb-10">
        <Link passHref href="/">
          <a>
            <h1 className="text-6xl text-center text-amber-400" id="titleContainer">{title}</h1>
          </a>
        </Link>
      </header>

      <main className="container mx-auto">
        {children}
      </main>

      <footer className="flex justify-center items-center mt-10">
        <p className='footerContent'>Made with ♥ by <Link passHref href="https://twitter.com/Shivamkatare_27">Shivam Katare</Link></p>
      </footer>
    </div>
  );
};

export default Layout;
